#!/bin/bash
set -e
initfile=/etc/rundeck.init
chmod 1777 /tmp

# chown directories and files that might be coming from volumes
chown -R rundeck:rundeck /etc/rundeck
chown -R rundeck:rundeck /var/rundeck
chown -R rundeck:adm /var/log/rundeck
chown -R rundeck:rundeck /var/lib/rundeck
chown -R rundeck:rundeck /opt/rundeck-defaults


if [ ! -f "${initfile}" ]; then
   SERVER_URL=${SERVER_URL:-"https://0.0.0.0:4443"}
   DATABASE_URL=${DATABASE_URL:-""}
   RUNDECK_PASSWORD=${RUNDECK_PASSWORD:-"rundeck"}
   
   echo "=>Initializing rundeck - This may take a few minutes"
   if [ ! -f /var/lib/rundeck/.ssh/id_rsa -a "{$RUNDECK_SSH_KEY}" == "{}" ]; then
       echo "=>Generating rundeck key"
       sudo -u rundeck ssh-keygen -t rsa -b 4096 -f /var/lib/rundeck/.ssh/id_rsa -N ''
   elif [ ! -f /var/lib/rundeck/.ssh/id_rsa -a "{$RUNDECK_SSH_KEY}" == "{}" ]; then
	echo "$RUNDECK_SSH_KEY" > /var/lib/rundeck/.ssh/id_rsa
   fi
   
   if [ "$(ls -A /etc/rundeck)" ]; then
       echo "=>/etc/rundeck check OK"
   else
       echo "=>/etc/rundeck empty...setting up defaults"
       cp -R /opt/rundeck-defaults/* /etc/rundeck
       chown -R rundeck:rundeck /etc/rundeck
   fi

   if [ ! -f /etc/rundeck/ssl/truststore ]; then
       echo "=>Generating ssl cert"
       sudo -u rundeck keytool -keystore /etc/rundeck/ssl/keystore -alias rundeck -genkey -keyalg RSA -keypass adminadmin -storepass adminadmin -dname "cn=localhost, o=OME, c=DE" && \
       cp /etc/rundeck/ssl/keystore /etc/rundeck/ssl/truststore
   fi

   sed -i 's,grails.serverURL\=.*,grails.serverURL\='${SERVER_URL}',g' /etc/rundeck/rundeck-config.properties
   sed -i 's,dataSource.dbCreate.*,,g' /etc/rundeck/rundeck-config.properties
   sed -i 's,dataSource.url = .*,dataSource.url = '${DATABASE_URL}',g' /etc/rundeck/rundeck-config.properties
   echo "dataSource.username = rundeck" >> /etc/rundeck/rundeck-config.properties
   echo "dataSource.password = ${RUNDECK_PASSWORD}" >> /etc/rundeck/rundeck-config.properties

   echo "framework.plugin.ExecutionFileStorage.org.rundeck.amazon-s3.bucket = ${RUNDECK_S3_BUCKET}" >> /etc/rundeck/framework.properties
   echo "framework.plugin.ExecutionFileStorage.org.rundeck.amazon-s3.path = ${RUNDECK_S3_PATH}" >> /etc/rundeck/framework.properies

   echo -e "\n\n\n"
   echo "==================================================================="
   if [ -f /var/lib/rundeck/.ssh/id_rsa.pub ]; then echo "Rundeck public key:"; cat /var/lib/rundeck/.ssh/id_rsa.pub; fi
   echo "Server URL set to ${SERVER_URL}"
   echo "==================================================================="

   cat /etc/rundeck/framework.properties

   touch ${initfile}
fi

echo "Starting Supervisor.  You can safely CTRL-C and the container will continue to run with or without the -d (daemon) option"

. /etc/rundeck/profile
DAEMON="${JAVA_HOME:-/usr}/bin/java"
DAEMON_ARGS="${RDECK_JVM} -cp ${BOOTSTRAP_CP} com.dtolabs.rundeck.RunServer /var/lib/rundeck 4440"
rundeckd="$DAEMON $DAEMON_ARGS"
cd /var/log/rundeck
su -s /bin/bash rundeck -c "$rundeckd"
